### Calculate the phone bill total using the specified price plan data.
POST http://localhost:3033/api/phonebill/
Content-Type: application/json

{
    "price_plan": "sms_kick_100",
    "actions" : "call, sms, call"
}
### Return a list of all the available price plans.
GET http://localhost:3033/api/price_plans/
Content-Type: application/json


### create price_plan
http://localhost:4001/api/price_plan/create

{
    "name": "sms_kick_100",
    "call_cost" : 2.65,
    "sms_cost": 0.45
}
### Update a price plan.
Content-Type: application/json
{
    "name": "sms_kick_100",
    "call_cost" : 2.65,
    "sms_cost": 0.45
}
### Delete a price plan
Content-Type: application/json
{
    "id": 17
}

